### ISSUE TITLE
Stuck at Started to download icomoon.zip

### ISSUE THREAD

**Issue by xrado** [Yuyz0112/icomoon-cli#4] opened 2018-10-16 12:22 UTC
The script used to work week or two ago, but today it just waits at [icomoon-cli] Started to download icomoon.zip and nothing happens

**Comment by xrado** [comment] 2018-10-16 12:32
I found the issues. I all SVG are not ok containing strokes, then you get a warning dialog 
"Strokes get ignored when generating fonts. 
You can convert them to fills to prevent this.
Would you like to deselect icons containing strokes?"

.. which breaks the flow.

**Comment by Yuyz0112** [comment] 2018-10-17 02:09
I think we could handle this by check the warning dialog and display the information in CLI's console log.

Any suggestions?

**Comment by xrado** [comment] 2018-10-17 09:19
Must be something else. I've removed all the icons with stroke, warning dialog is gone, but still doesn't work. Downloading never ends.

**Comment by xrado** [comment] 2018-10-17 09:30
Interesting, with `visible: true` worked smoothly with no problems, turning it back to false still stucks at downloading

**Comment by Yuyz0112** [comment] 2018-10-18 03:15
strange...
Would you mind run `npm test` to check whether the test suite could pass in your env? Then we can know is this an icon issue or env issue.

**Comment by xrado** [comment] 2018-10-18 06:15
tests pass, but today also works with my icons (I removed some unnecessary icons, might be it)

**Comment by Yuyz0112** [comment] 2018-10-18 06:46
ok.
If you want to dig into the root cause and like to share your selection file, maybe I can check it in the weekend. Or you can just close this issue:)

**Closed** 2018-10-18 09:18 UTC

**Comment by ptimatth** [comment] 2020-03-17 11:06
Hi, after my last PR? i have recreate this issue. :/ 
It seem to be produce when the browser is too fast to send the reload event.

I will make a ne w PR.
